#############################################################################
# Makefile for building: gateway-demo
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  gateway-demo.pro
# Template: subdirs
# Command: C:\Qt\Qt5.14.2\5.14.2\mingw73_32\bin\qmake.exe -o Makefile gateway-demo.pro -spec win32-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\Qt5.14.2\5.14.2\mingw73_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\Qt5.14.2\5.14.2\mingw73_32\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\Qt5.14.2\5.14.2\mingw73_32\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-apps-rk3568_dtu_demo \
		sub-apps-rk3568_edge_gateway_demo \
		sub-apps-pc_config_tool


sub-apps-rk3568_dtu_demo-qmake_all:  FORCE
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++
	cd apps\rk3568_dtu_demo\ && $(MAKE) -f Makefile qmake_all
sub-apps-rk3568_dtu_demo: FORCE
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile
sub-apps-rk3568_dtu_demo-make_first-ordered: FORCE
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile 
sub-apps-rk3568_dtu_demo-make_first: FORCE
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile 
sub-apps-rk3568_dtu_demo-all-ordered: FORCE
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile all
sub-apps-rk3568_dtu_demo-all: FORCE
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile all
sub-apps-rk3568_dtu_demo-clean-ordered: FORCE
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile clean
sub-apps-rk3568_dtu_demo-clean: FORCE
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile clean
sub-apps-rk3568_dtu_demo-distclean-ordered: FORCE
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile distclean
sub-apps-rk3568_dtu_demo-distclean: FORCE
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile distclean
sub-apps-rk3568_dtu_demo-install_subtargets-ordered: FORCE
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile install
sub-apps-rk3568_dtu_demo-install_subtargets: FORCE
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile install
sub-apps-rk3568_dtu_demo-uninstall_subtargets-ordered: FORCE
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile uninstall
sub-apps-rk3568_dtu_demo-uninstall_subtargets: FORCE
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile uninstall
sub-apps-rk3568_edge_gateway_demo-qmake_all: sub-apps-rk3568_dtu_demo-qmake_all FORCE
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++
	cd apps\rk3568_edge_gateway_demo\ && $(MAKE) -f Makefile qmake_all
sub-apps-rk3568_edge_gateway_demo: FORCE
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile
sub-apps-rk3568_edge_gateway_demo-make_first-ordered: sub-apps-rk3568_dtu_demo-make_first-ordered  FORCE
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile 
sub-apps-rk3568_edge_gateway_demo-make_first: FORCE
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile 
sub-apps-rk3568_edge_gateway_demo-all-ordered: sub-apps-rk3568_dtu_demo-all-ordered  FORCE
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile all
sub-apps-rk3568_edge_gateway_demo-all: FORCE
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile all
sub-apps-rk3568_edge_gateway_demo-clean-ordered: sub-apps-rk3568_dtu_demo-clean-ordered  FORCE
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile clean
sub-apps-rk3568_edge_gateway_demo-clean: FORCE
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile clean
sub-apps-rk3568_edge_gateway_demo-distclean-ordered: sub-apps-rk3568_dtu_demo-distclean-ordered  FORCE
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile distclean
sub-apps-rk3568_edge_gateway_demo-distclean: FORCE
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile distclean
sub-apps-rk3568_edge_gateway_demo-install_subtargets-ordered: sub-apps-rk3568_dtu_demo-install_subtargets-ordered  FORCE
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile install
sub-apps-rk3568_edge_gateway_demo-install_subtargets: FORCE
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile install
sub-apps-rk3568_edge_gateway_demo-uninstall_subtargets-ordered: sub-apps-rk3568_dtu_demo-uninstall_subtargets-ordered  FORCE
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile uninstall
sub-apps-rk3568_edge_gateway_demo-uninstall_subtargets: FORCE
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile uninstall
sub-apps-pc_config_tool-qmake_all: sub-apps-rk3568_edge_gateway_demo-qmake_all FORCE
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++
	cd apps\pc_config_tool\ && $(MAKE) -f Makefile qmake_all
sub-apps-pc_config_tool: FORCE
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile
sub-apps-pc_config_tool-make_first-ordered: sub-apps-rk3568_edge_gateway_demo-make_first-ordered  FORCE
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile 
sub-apps-pc_config_tool-make_first: FORCE
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile 
sub-apps-pc_config_tool-all-ordered: sub-apps-rk3568_edge_gateway_demo-all-ordered  FORCE
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile all
sub-apps-pc_config_tool-all: FORCE
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile all
sub-apps-pc_config_tool-clean-ordered: sub-apps-rk3568_edge_gateway_demo-clean-ordered  FORCE
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile clean
sub-apps-pc_config_tool-clean: FORCE
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile clean
sub-apps-pc_config_tool-distclean-ordered: sub-apps-rk3568_edge_gateway_demo-distclean-ordered  FORCE
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile distclean
sub-apps-pc_config_tool-distclean: FORCE
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile distclean
sub-apps-pc_config_tool-install_subtargets-ordered: sub-apps-rk3568_edge_gateway_demo-install_subtargets-ordered  FORCE
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile install
sub-apps-pc_config_tool-install_subtargets: FORCE
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile install
sub-apps-pc_config_tool-uninstall_subtargets-ordered: sub-apps-rk3568_edge_gateway_demo-uninstall_subtargets-ordered  FORCE
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile uninstall
sub-apps-pc_config_tool-uninstall_subtargets: FORCE
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile uninstall

Makefile: gateway-demo.pro C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/win32-g++/qmake.conf C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/spec_pre.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/qdevice.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/device_config.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/sanitize.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/gcc-base.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/g++-base.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/angle.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/win32/windows_vulkan_sdk.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/windows-vulkan.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/g++-win32.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/windows-desktop.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/qconfig.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3danimation.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3danimation_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dcore.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dextras.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dextras_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dinput.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dlogic.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquick.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickanimation.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickextras.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3drender.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3drender_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bodymovin_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_charts.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_charts_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_datavisualization.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_datavisualization_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_dbus.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_edid_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gamepad.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_location.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_location_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_networkauth.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_networkauth_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioningquick.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioningquick_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_purchasing.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_purchasing_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmldebug_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlmodels.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3d.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3d_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3drender.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3drender_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dutils.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickshapes_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quicktemplates2.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_remoteobjects.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_repparser.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_repparser_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_scxml.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_scxml_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialbus.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_texttospeech.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_webchannel.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_zlib_private.pri \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/qt_functions.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/qt_config.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/win32-g++/qmake.conf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/spec_post.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/exclusive_builds.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/toolchain.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/default_pre.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/win32/default_pre.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/resolve_config.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/default_post.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/precompile_header.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/warn_on.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/qmake_use.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/file_copies.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/win32/windows.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/testcase_targets.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/exceptions.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/yacc.prf \
		C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/lex.prf \
		gateway-demo.pro
	$(QMAKE) -o Makefile gateway-demo.pro -spec win32-g++
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/spec_pre.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/qdevice.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/device_config.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/sanitize.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/gcc-base.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/g++-base.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/angle.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/win32/windows_vulkan_sdk.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/windows-vulkan.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/g++-win32.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/common/windows-desktop.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/qconfig.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3danimation.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3danimation_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dcore.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dcore_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dextras.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dextras_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dinput.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dinput_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dlogic.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquick.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquick_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickanimation.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickextras.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickextras_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickinput.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickrender.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickscene2d.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3drender.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_3drender_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axbase.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axbase_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axcontainer.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axserver.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_axserver_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bluetooth.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bodymovin_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_charts.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_charts_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_core.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_datavisualization.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_datavisualization_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_dbus.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_dbus_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_designer.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_designer_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_edid_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_egl_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gamepad.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gamepad_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_help.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_help_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_location.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_location_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimedia.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_network.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_networkauth.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_networkauth_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_nfc.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_nfc_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_openglextensions.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_packetprotocol_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioning.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioning_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioningquick.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_positioningquick_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_purchasing.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_purchasing_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qml.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qml_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmldebug_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlmodels.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlmodels_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmltest.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlworkerscript.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3d.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3d_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dassetimport.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3drender.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3drender_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3druntimerender.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dutils.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick3dutils_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quick_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickshapes_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quicktemplates2.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_remoteobjects.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_remoteobjects_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_repparser.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_repparser_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_scxml.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_scxml_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sensors.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sensors_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialbus.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialbus_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialport.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_serialport_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_svg.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_svg_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_texttospeech.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_texttospeech_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_theme_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_uiplugin.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_uitools.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_uitools_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_virtualkeyboard.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_webchannel.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_webchannel_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_websockets.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_websockets_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_winextras.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_winextras_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/modules/qt_lib_zlib_private.pri:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/qt_functions.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/qt_config.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/win32-g++/qmake.conf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/spec_post.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/exclusive_builds.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/toolchain.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/default_pre.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/win32/default_pre.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/resolve_config.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/default_post.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/precompile_header.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/warn_on.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/qmake_use.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/file_copies.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/win32/windows.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/testcase_targets.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/exceptions.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/yacc.prf:
C:/Qt/Qt5.14.2/5.14.2/mingw73_32/mkspecs/features/lex.prf:
gateway-demo.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile gateway-demo.pro -spec win32-g++

qmake_all: sub-apps-rk3568_dtu_demo-qmake_all sub-apps-rk3568_edge_gateway_demo-qmake_all sub-apps-pc_config_tool-qmake_all FORCE

make_first: sub-apps-rk3568_dtu_demo-make_first-ordered sub-apps-rk3568_edge_gateway_demo-make_first-ordered sub-apps-pc_config_tool-make_first-ordered  FORCE
all: sub-apps-rk3568_dtu_demo-all-ordered sub-apps-rk3568_edge_gateway_demo-all-ordered sub-apps-pc_config_tool-all-ordered  FORCE
clean: sub-apps-rk3568_dtu_demo-clean-ordered sub-apps-rk3568_edge_gateway_demo-clean-ordered sub-apps-pc_config_tool-clean-ordered  FORCE
distclean: sub-apps-rk3568_dtu_demo-distclean-ordered sub-apps-rk3568_edge_gateway_demo-distclean-ordered sub-apps-pc_config_tool-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-apps-rk3568_dtu_demo-install_subtargets-ordered sub-apps-rk3568_edge_gateway_demo-install_subtargets-ordered sub-apps-pc_config_tool-install_subtargets-ordered FORCE
uninstall_subtargets: sub-apps-rk3568_dtu_demo-uninstall_subtargets-ordered sub-apps-rk3568_edge_gateway_demo-uninstall_subtargets-ordered sub-apps-pc_config_tool-uninstall_subtargets-ordered FORCE

sub-apps-rk3568_dtu_demo-debug_ordered:
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile debug
sub-apps-rk3568_edge_gateway_demo-debug_ordered: sub-apps-rk3568_dtu_demo-debug_ordered 
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile debug
sub-apps-pc_config_tool-debug_ordered: sub-apps-rk3568_edge_gateway_demo-debug_ordered 
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile debug
debug: sub-apps-rk3568_dtu_demo-debug_ordered sub-apps-rk3568_edge_gateway_demo-debug_ordered sub-apps-pc_config_tool-debug_ordered

sub-apps-rk3568_dtu_demo-release_ordered:
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile release
sub-apps-rk3568_edge_gateway_demo-release_ordered: sub-apps-rk3568_dtu_demo-release_ordered 
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile release
sub-apps-pc_config_tool-release_ordered: sub-apps-rk3568_edge_gateway_demo-release_ordered 
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile release
release: sub-apps-rk3568_dtu_demo-release_ordered sub-apps-rk3568_edge_gateway_demo-release_ordered sub-apps-pc_config_tool-release_ordered

sub-apps-rk3568_dtu_demo-check_ordered:
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile check
sub-apps-rk3568_edge_gateway_demo-check_ordered: sub-apps-rk3568_dtu_demo-check_ordered 
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile check
sub-apps-pc_config_tool-check_ordered: sub-apps-rk3568_edge_gateway_demo-check_ordered 
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile check
check: sub-apps-rk3568_dtu_demo-check_ordered sub-apps-rk3568_edge_gateway_demo-check_ordered sub-apps-pc_config_tool-check_ordered

sub-apps-rk3568_dtu_demo-benchmark_ordered:
	@if not exist apps\rk3568_dtu_demo\ mkdir apps\rk3568_dtu_demo\ & if not exist apps\rk3568_dtu_demo\ exit 1
	cd apps\rk3568_dtu_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_dtu_demo\rk3568_dtu_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile benchmark
sub-apps-rk3568_edge_gateway_demo-benchmark_ordered: sub-apps-rk3568_dtu_demo-benchmark_ordered 
	@if not exist apps\rk3568_edge_gateway_demo\ mkdir apps\rk3568_edge_gateway_demo\ & if not exist apps\rk3568_edge_gateway_demo\ exit 1
	cd apps\rk3568_edge_gateway_demo\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\rk3568_edge_gateway_demo\rk3568_edge_gateway_demo.pro -spec win32-g++ ) && $(MAKE) -f Makefile benchmark
sub-apps-pc_config_tool-benchmark_ordered: sub-apps-rk3568_edge_gateway_demo-benchmark_ordered 
	@if not exist apps\pc_config_tool\ mkdir apps\pc_config_tool\ & if not exist apps\pc_config_tool\ exit 1
	cd apps\pc_config_tool\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\project\gateway-dev\ai-gateway2026\apps\pc_config_tool\pc_config_tool.pro -spec win32-g++ ) && $(MAKE) -f Makefile benchmark
benchmark: sub-apps-rk3568_dtu_demo-benchmark_ordered sub-apps-rk3568_edge_gateway_demo-benchmark_ordered sub-apps-pc_config_tool-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

